export default [
  {
    name: 'Brand name 1',
    price: '$2,995',
    description: 'Product description here',
    colors: 0,
    id: 'acc1',
    img: './img/main__popular-finds_item1-back.png',
  },
  {
    name: 'Brand name 2',
    price: '$2,995',
    description: 'Product description here',
    colors: 0,
    id: 'acc2',
    img: './img/main__popular-finds_item2-back.png',
  },
  {
    name: 'Brand name 3',
    price: '$2,995',
    description: 'Product description here',
    colors: 0,
    id: 'acc3',
    img: './img/main__popular-finds_item3-back.png',
  },
  {
    name: 'Brand name 4',
    price: '$2,995',
    description: 'Product description here',
    colors: 0,
    id: 'acc4',
    img: './img/main__popular-finds_item4-back.png',
  },
  {
    name: 'Brand name 5',
    price: '$2,995',
    description: 'Product description here',
    colors: 0,
    id: 'acc5',
    img: './img/main__popular-finds_item4-back.png',
  },
  {
    name: 'Brand name 6',
    price: '$2,995',
    description: 'Product description here',
    colors: 0,
    id: 'acc6',
    img: './img/main__popular-finds_item4-back.png',
  },
  {
    name: 'Brand name 7',
    price: '$2,995',
    description: 'Product description here',
    colors: 0,
    id: 'acc7',
    img: './img/main__popular-finds_item4-back.png',
  },
  {
    name: 'Brand name 8',
    price: '$2,995',
    description: 'Product description here',
    colors: 0,
    id: 'acc8',
    img: './img/main__popular-finds_item4-back.png',
  },
  {
    name: 'Brand name 9',
    price: '$2,995',
    description: 'Product description here',
    colors: 0,
    id: 'acc9',
    img: './img/main__popular-finds_item4-back.png',
  },
];
