export default [
  {
    name: 'Brand name 1',
    price: '$2,995',
    description: 'Product description here',
    colors: 0,
    id: Math.random(),
    img: './img/main__popular-finds_item1-back.png',
  },
  {
    name: 'Brand name 2',
    price: '$2,995',
    description: 'Product description here',
    colors: 0,
    id: Math.random(),
    img: './img/main__popular-finds_item2-back.png',
  },
  {
    name: 'Brand name 3',
    price: '$2,995',
    description: 'Product description here',
    colors: 0,
    id: Math.random(),
    img: './img/main__popular-finds_item3-back.png',
  },
  {
    name: 'Brand name 4',
    price: '$2,995',
    description: 'Product description here',
    colors: 0,
    id: Math.random(),
    img: './img/main__popular-finds_item4-back.png',
  },
  {
    name: 'Brand name 5',
    price: '$2,995',
    description: 'Product description here',
    colors: 0,
    id: Math.random(),
    img: './img/main__popular-finds_item4-back.png',
  },
  {
    name: 'Brand name 6',
    price: '$2,995',
    description: 'Product description here',
    colors: 0,
    id: Math.random(),
    img: './img/main__popular-finds_item4-back.png',
  },
  {
    name: 'Brand name 7',
    price: '$2,995',
    description: 'Product description here',
    colors: 0,
    id: Math.random(),
    img: './img/main__popular-finds_item4-back.png',
  },
  {
    name: 'Brand name 8',
    price: '$2,995',
    description: 'Product description here',
    colors: 0,
    id: Math.random(),
    img: './img/main__popular-finds_item4-back.png',
  },
  {
    name: 'Brand name 9',
    price: '$2,995',
    description: 'Product description here',
    colors: 0,
    id: Math.random(),
    img: './img/main__popular-finds_item4-back.png',
  },
];
