export default [
  {
    name: 'Brand name',
    price: '$2,995',
    description: 'Product description here',
    colors: 0,
    id: 'guitar1',
    img: '/img/main__section_guitar1-back.png',
  },
  {
    name: 'Brand name',
    price: '$2,995',
    description: 'Product description here',
    colors: 0,
    id: 'guitar2',
    img: '/img/main__section_guitar2-back.png',
  },
  {
    name: 'Brand name',
    price: '$2,995',
    description: 'Product description here',
    colors: 0,
    id: 'guitar3',
    img: '/img/main__section_guitar3-back.png',
  },
  {
    name: 'Brand name',
    price: '$2,995',
    description: 'Product description here',
    colors: 0,
    id: 'guitar4',
    img: '/img/main__section_guitar4-back.png',
  },
  {
    name: 'Brand name',
    price: '$2,995',
    description: 'Product description here',
    colors: 0,
    id: 'guitar5',
    img: '/img/main__section_guitar5-back.png',
  },
  {
    name: 'Brand name',
    price: '$2,995',
    description: 'Product description here',
    colors: 0,
    id: 'guitar6',
    img: '/img/main__section_guitar6-back.png',
  },
  {
    name: 'Brand name',
    price: '$2,995',
    description: 'Product description here',
    colors: 0,
    id: 'guitar7',
    img: '/img/main__section_guitar7-back.png',
  },
  {
    name: 'Brand name',
    price: '$2,995',
    description: 'Product description here',
    colors: 0,
    id: 'guitar8',
    img: '/img/main__section_guitar8-back.png',
  },
  {
    name: 'Brand name',
    price: '$2,995',
    description: 'Product description here',
    colors: 0,
    id: 'guitar9',
    img: '/img/main__section_guitar9-back.png',
  },
];
